// Auto-generated NUTS 1, 2, 3 and Metropolitan Areas mapping for all 308 concelhos.
const NUTS_DATA = {
  "0101": { n1: "Continente", n2: "Centro", n3: "Região de Aveiro", am: null },
  "0102": { n1: "Continente", n2: "Centro", n3: "Região de Aveiro", am: null },
  "0103": { n1: "Continente", n2: "Centro", n3: "Região de Aveiro", am: null },
  "0104": { n1: "Continente", n2: "Norte", n3: "Área Metropolitana do Porto", am: "AMP" },
  "0105": { n1: "Continente", n2: "Centro", n3: "Região de Aveiro", am: null },
  "0106": { n1: "Continente", n2: "Norte", n3: "Tâmega e Sousa", am: null },
  "0107": { n1: "Continente", n2: "Norte", n3: "Área Metropolitana do Porto", am: "AMP" },
  "0108": { n1: "Continente", n2: "Centro", n3: "Região de Aveiro", am: null },
  "0109": { n1: "Continente", n2: "Norte", n3: "Área Metropolitana do Porto", am: "AMP" },
  "0110": { n1: "Continente", n2: "Centro", n3: "Região de Aveiro", am: null },
  "0111": { n1: "Continente", n2: "Centro", n3: "Região de Coimbra", am: null },
  "0112": { n1: "Continente", n2: "Centro", n3: "Região de Aveiro", am: null },
  "0113": { n1: "Continente", n2: "Norte", n3: "Área Metropolitana do Porto", am: "AMP" },
  "0114": { n1: "Continente", n2: "Centro", n3: "Região de Aveiro", am: null },
  "0115": { n1: "Continente", n2: "Centro", n3: "Região de Aveiro", am: null },
  "0116": { n1: "Continente", n2: "Norte", n3: "Área Metropolitana do Porto", am: "AMP" },
  "0117": { n1: "Continente", n2: "Centro", n3: "Região de Aveiro", am: null },
  "0118": { n1: "Continente", n2: "Centro", n3: "Região de Aveiro", am: null },
  "0119": { n1: "Continente", n2: "Norte", n3: "Área Metropolitana do Porto", am: "AMP" },
  "0201": { n1: "Continente", n2: "Alentejo", n3: "Baixo Alentejo", am: null },
  "0202": { n1: "Continente", n2: "Alentejo", n3: "Baixo Alentejo", am: null },
  "0203": { n1: "Continente", n2: "Alentejo", n3: "Baixo Alentejo", am: null },
  "0204": { n1: "Continente", n2: "Alentejo", n3: "Baixo Alentejo", am: null },
  "0205": { n1: "Continente", n2: "Alentejo", n3: "Baixo Alentejo", am: null },
  "0206": { n1: "Continente", n2: "Alentejo", n3: "Baixo Alentejo", am: null },
  "0207": { n1: "Continente", n2: "Alentejo", n3: "Baixo Alentejo", am: null },
  "0208": { n1: "Continente", n2: "Alentejo", n3: "Baixo Alentejo", am: null },
  "0209": { n1: "Continente", n2: "Alentejo", n3: "Baixo Alentejo", am: null },
  "0210": { n1: "Continente", n2: "Alentejo", n3: "Baixo Alentejo", am: null },
  "0211": { n1: "Continente", n2: "Alentejo", n3: "Alentejo Litoral", am: null },
  "0212": { n1: "Continente", n2: "Alentejo", n3: "Baixo Alentejo", am: null },
  "0213": { n1: "Continente", n2: "Alentejo", n3: "Baixo Alentejo", am: null },
  "0214": { n1: "Continente", n2: "Alentejo", n3: "Baixo Alentejo", am: null },
  "0301": { n1: "Continente", n2: "Norte", n3: "Cávado", am: null },
  "0302": { n1: "Continente", n2: "Norte", n3: "Cávado", am: null },
  "0303": { n1: "Continente", n2: "Norte", n3: "Cávado", am: null },
  "0304": { n1: "Continente", n2: "Norte", n3: "Ave", am: null },
  "0305": { n1: "Continente", n2: "Norte", n3: "Tâmega e Sousa", am: null },
  "0306": { n1: "Continente", n2: "Norte", n3: "Cávado", am: null },
  "0307": { n1: "Continente", n2: "Norte", n3: "Ave", am: null },
  "0308": { n1: "Continente", n2: "Norte", n3: "Ave", am: null },
  "0309": { n1: "Continente", n2: "Norte", n3: "Ave", am: null },
  "0310": { n1: "Continente", n2: "Norte", n3: "Cávado", am: null },
  "0311": { n1: "Continente", n2: "Norte", n3: "Ave", am: null },
  "0312": { n1: "Continente", n2: "Norte", n3: "Ave", am: null },
  "0313": { n1: "Continente", n2: "Norte", n3: "Cávado", am: null },
  "0314": { n1: "Continente", n2: "Norte", n3: "Ave", am: null },
  "0401": { n1: "Continente", n2: "Norte", n3: "Terras de Trás-os-Montes", am: null },
  "0402": { n1: "Continente", n2: "Norte", n3: "Terras de Trás-os-Montes", am: null },
  "0403": { n1: "Continente", n2: "Norte", n3: "Douro", am: null },
  "0404": { n1: "Continente", n2: "Norte", n3: "Douro", am: null },
  "0405": { n1: "Continente", n2: "Norte", n3: "Terras de Trás-os-Montes", am: null },
  "0406": { n1: "Continente", n2: "Norte", n3: "Terras de Trás-os-Montes", am: null },
  "0407": { n1: "Continente", n2: "Norte", n3: "Terras de Trás-os-Montes", am: null },
  "0408": { n1: "Continente", n2: "Norte", n3: "Terras de Trás-os-Montes", am: null },
  "0409": { n1: "Continente", n2: "Norte", n3: "Douro", am: null },
  "0410": { n1: "Continente", n2: "Norte", n3: "Terras de Trás-os-Montes", am: null },
  "0411": { n1: "Continente", n2: "Norte", n3: "Terras de Trás-os-Montes", am: null },
  "0412": { n1: "Continente", n2: "Norte", n3: "Terras de Trás-os-Montes", am: null },
  "0501": { n1: "Continente", n2: "Centro", n3: "Beiras e Serra da Estrela", am: null },
  "0502": { n1: "Continente", n2: "Centro", n3: "Beira Baixa", am: null },
  "0503": { n1: "Continente", n2: "Centro", n3: "Beiras e Serra da Estrela", am: null },
  "0504": { n1: "Continente", n2: "Centro", n3: "Beiras e Serra da Estrela", am: null },
  "0505": { n1: "Continente", n2: "Centro", n3: "Beira Baixa", am: null },
  "0506": { n1: "Continente", n2: "Centro", n3: "Beira Baixa", am: null },
  "0507": { n1: "Continente", n2: "Centro", n3: "Beira Baixa", am: null },
  "0508": { n1: "Continente", n2: "Centro", n3: "Beira Baixa", am: null },
  "0509": { n1: "Continente", n2: "Centro", n3: "Beira Baixa", am: null },
  "0510": { n1: "Continente", n2: "Centro", n3: "Beira Baixa", am: null },
  "0511": { n1: "Continente", n2: "Centro", n3: "Beira Baixa", am: null },
  "0601": { n1: "Continente", n2: "Centro", n3: "Região de Coimbra", am: null },
  "0602": { n1: "Continente", n2: "Centro", n3: "Região de Coimbra", am: null },
  "0603": { n1: "Continente", n2: "Centro", n3: "Região de Coimbra", am: null },
  "0604": { n1: "Continente", n2: "Centro", n3: "Região de Coimbra", am: null },
  "0605": { n1: "Continente", n2: "Centro", n3: "Região de Coimbra", am: null },
  "0606": { n1: "Continente", n2: "Centro", n3: "Região de Coimbra", am: null },
  "0607": { n1: "Continente", n2: "Centro", n3: "Região de Coimbra", am: null },
  "0608": { n1: "Continente", n2: "Centro", n3: "Região de Coimbra", am: null },
  "0609": { n1: "Continente", n2: "Centro", n3: "Região de Coimbra", am: null },
  "0610": { n1: "Continente", n2: "Centro", n3: "Região de Coimbra", am: null },
  "0611": { n1: "Continente", n2: "Centro", n3: "Região de Coimbra", am: null },
  "0612": { n1: "Continente", n2: "Centro", n3: "Região de Coimbra", am: null },
  "0613": { n1: "Continente", n2: "Centro", n3: "Região de Coimbra", am: null },
  "0614": { n1: "Continente", n2: "Centro", n3: "Região de Coimbra", am: null },
  "0615": { n1: "Continente", n2: "Centro", n3: "Região de Coimbra", am: null },
  "0616": { n1: "Continente", n2: "Centro", n3: "Região de Coimbra", am: null },
  "0617": { n1: "Continente", n2: "Centro", n3: "Região de Coimbra", am: null },
  "0701": { n1: "Continente", n2: "Alentejo", n3: "Alentejo Central", am: null },
  "0702": { n1: "Continente", n2: "Alentejo", n3: "Alentejo Central", am: null },
  "0703": { n1: "Continente", n2: "Alentejo", n3: "Alentejo Central", am: null },
  "0704": { n1: "Continente", n2: "Alentejo", n3: "Alentejo Central", am: null },
  "0705": { n1: "Continente", n2: "Alentejo", n3: "Alentejo Central", am: null },
  "0706": { n1: "Continente", n2: "Alentejo", n3: "Alentejo Central", am: null },
  "0707": { n1: "Continente", n2: "Alentejo", n3: "Alentejo Central", am: null },
  "0708": { n1: "Continente", n2: "Alentejo", n3: "Alentejo Central", am: null },
  "0709": { n1: "Continente", n2: "Alentejo", n3: "Alentejo Central", am: null },
  "0710": { n1: "Continente", n2: "Alentejo", n3: "Alentejo Central", am: null },
  "0711": { n1: "Continente", n2: "Alentejo", n3: "Alentejo Central", am: null },
  "0712": { n1: "Continente", n2: "Alentejo", n3: "Alentejo Central", am: null },
  "0713": { n1: "Continente", n2: "Alentejo", n3: "Alentejo Central", am: null },
  "0714": { n1: "Continente", n2: "Alentejo", n3: "Alentejo Central", am: null },
  "0801": { n1: "Continente", n2: "Algarve", n3: "Algarve", am: null },
  "0802": { n1: "Continente", n2: "Algarve", n3: "Algarve", am: null },
  "0803": { n1: "Continente", n2: "Algarve", n3: "Algarve", am: null },
  "0804": { n1: "Continente", n2: "Algarve", n3: "Algarve", am: null },
  "0805": { n1: "Continente", n2: "Algarve", n3: "Algarve", am: null },
  "0806": { n1: "Continente", n2: "Algarve", n3: "Algarve", am: null },
  "0807": { n1: "Continente", n2: "Algarve", n3: "Algarve", am: null },
  "0808": { n1: "Continente", n2: "Algarve", n3: "Algarve", am: null },
  "0809": { n1: "Continente", n2: "Algarve", n3: "Algarve", am: null },
  "0810": { n1: "Continente", n2: "Algarve", n3: "Algarve", am: null },
  "0811": { n1: "Continente", n2: "Algarve", n3: "Algarve", am: null },
  "0812": { n1: "Continente", n2: "Algarve", n3: "Algarve", am: null },
  "0813": { n1: "Continente", n2: "Algarve", n3: "Algarve", am: null },
  "0814": { n1: "Continente", n2: "Algarve", n3: "Algarve", am: null },
  "0815": { n1: "Continente", n2: "Algarve", n3: "Algarve", am: null },
  "0816": { n1: "Continente", n2: "Algarve", n3: "Algarve", am: null },
  "0901": { n1: "Continente", n2: "Centro", n3: "Viseu Dão Lafões", am: null },
  "0902": { n1: "Continente", n2: "Centro", n3: "Beiras e Serra da Estrela", am: null },
  "0903": { n1: "Continente", n2: "Centro", n3: "Beiras e Serra da Estrela", am: null },
  "0904": { n1: "Continente", n2: "Centro", n3: "Beiras e Serra da Estrela", am: null },
  "0905": { n1: "Continente", n2: "Centro", n3: "Beiras e Serra da Estrela", am: null },
  "0906": { n1: "Continente", n2: "Centro", n3: "Beiras e Serra da Estrela", am: null },
  "0907": { n1: "Continente", n2: "Centro", n3: "Beiras e Serra da Estrela", am: null },
  "0908": { n1: "Continente", n2: "Centro", n3: "Beiras e Serra da Estrela", am: null },
  "0909": { n1: "Continente", n2: "Centro", n3: "Beiras e Serra da Estrela", am: null },
  "0910": { n1: "Continente", n2: "Centro", n3: "Beiras e Serra da Estrela", am: null },
  "0911": { n1: "Continente", n2: "Centro", n3: "Beiras e Serra da Estrela", am: null },
  "0912": { n1: "Continente", n2: "Centro", n3: "Beiras e Serra da Estrela", am: null },
  "0913": { n1: "Continente", n2: "Centro", n3: "Beiras e Serra da Estrela", am: null },
  "0914": { n1: "Continente", n2: "Norte", n3: "Douro", am: null },
  "1001": { n1: "Continente", n2: "Oeste e Vale do Tejo", n3: "Oeste", am: null },
  "1002": { n1: "Continente", n2: "Centro", n3: "Região de Leiria", am: null },
  "1003": { n1: "Continente", n2: "Centro", n3: "Região de Leiria", am: null },
  "1004": { n1: "Continente", n2: "Centro", n3: "Região de Leiria", am: null },
  "1005": { n1: "Continente", n2: "Oeste e Vale do Tejo", n3: "Oeste", am: null },
  "1006": { n1: "Continente", n2: "Oeste e Vale do Tejo", n3: "Oeste", am: null },
  "1007": { n1: "Continente", n2: "Centro", n3: "Região de Leiria", am: null },
  "1008": { n1: "Continente", n2: "Centro", n3: "Região de Leiria", am: null },
  "1009": { n1: "Continente", n2: "Centro", n3: "Região de Leiria", am: null },
  "1010": { n1: "Continente", n2: "Centro", n3: "Região de Leiria", am: null },
  "1011": { n1: "Continente", n2: "Oeste e Vale do Tejo", n3: "Oeste", am: null },
  "1012": { n1: "Continente", n2: "Oeste e Vale do Tejo", n3: "Oeste", am: null },
  "1013": { n1: "Continente", n2: "Centro", n3: "Região de Leiria", am: null },
  "1014": { n1: "Continente", n2: "Oeste e Vale do Tejo", n3: "Oeste", am: null },
  "1015": { n1: "Continente", n2: "Centro", n3: "Região de Leiria", am: null },
  "1016": { n1: "Continente", n2: "Centro", n3: "Região de Leiria", am: null },
  "1101": { n1: "Continente", n2: "Oeste e Vale do Tejo", n3: "Oeste", am: null },
  "1102": { n1: "Continente", n2: "Oeste e Vale do Tejo", n3: "Oeste", am: null },
  "1103": { n1: "Continente", n2: "Oeste e Vale do Tejo", n3: "Lezíria do Tejo", am: null },
  "1104": { n1: "Continente", n2: "Oeste e Vale do Tejo", n3: "Oeste", am: null },
  "1105": { n1: "Continente", n2: "Área Metropolitana de Lisboa", n3: "Grande Lisboa", am: "AML" },
  "1106": { n1: "Continente", n2: "Área Metropolitana de Lisboa", n3: "Grande Lisboa", am: "AML" },
  "1107": { n1: "Continente", n2: "Área Metropolitana de Lisboa", n3: "Grande Lisboa", am: "AML" },
  "1108": { n1: "Continente", n2: "Oeste e Vale do Tejo", n3: "Oeste", am: null },
  "1109": { n1: "Continente", n2: "Área Metropolitana de Lisboa", n3: "Grande Lisboa", am: "AML" },
  "1110": { n1: "Continente", n2: "Área Metropolitana de Lisboa", n3: "Grande Lisboa", am: "AML" },
  "1111": { n1: "Continente", n2: "Área Metropolitana de Lisboa", n3: "Grande Lisboa", am: "AML" },
  "1112": { n1: "Continente", n2: "Oeste e Vale do Tejo", n3: "Oeste", am: null },
  "1113": { n1: "Continente", n2: "Oeste e Vale do Tejo", n3: "Oeste", am: null },
  "1114": { n1: "Continente", n2: "Área Metropolitana de Lisboa", n3: "Grande Lisboa", am: "AML" },
  "1115": { n1: "Continente", n2: "Área Metropolitana de Lisboa", n3: "Grande Lisboa", am: "AML" },
  "1116": { n1: "Continente", n2: "Área Metropolitana de Lisboa", n3: "Grande Lisboa", am: "AML" },
  "1201": { n1: "Continente", n2: "Alentejo", n3: "Alto Alentejo", am: null },
  "1202": { n1: "Continente", n2: "Alentejo", n3: "Alto Alentejo", am: null },
  "1203": { n1: "Continente", n2: "Alentejo", n3: "Alto Alentejo", am: null },
  "1204": { n1: "Continente", n2: "Alentejo", n3: "Alto Alentejo", am: null },
  "1205": { n1: "Continente", n2: "Alentejo", n3: "Alto Alentejo", am: null },
  "1206": { n1: "Continente", n2: "Alentejo", n3: "Alto Alentejo", am: null },
  "1207": { n1: "Continente", n2: "Alentejo", n3: "Alto Alentejo", am: null },
  "1208": { n1: "Continente", n2: "Alentejo", n3: "Alto Alentejo", am: null },
  "1209": { n1: "Continente", n2: "Alentejo", n3: "Alto Alentejo", am: null },
  "1210": { n1: "Continente", n2: "Alentejo", n3: "Alto Alentejo", am: null },
  "1211": { n1: "Continente", n2: "Alentejo", n3: "Alto Alentejo", am: null },
  "1212": { n1: "Continente", n2: "Alentejo", n3: "Alto Alentejo", am: null },
  "1213": { n1: "Continente", n2: "Alentejo", n3: "Alto Alentejo", am: null },
  "1214": { n1: "Continente", n2: "Alentejo", n3: "Alto Alentejo", am: null },
  "1215": { n1: "Continente", n2: "Alentejo", n3: "Alto Alentejo", am: null },
  "1301": { n1: "Continente", n2: "Norte", n3: "Tâmega e Sousa", am: null },
  "1302": { n1: "Continente", n2: "Norte", n3: "Tâmega e Sousa", am: null },
  "1303": { n1: "Continente", n2: "Norte", n3: "Tâmega e Sousa", am: null },
  "1304": { n1: "Continente", n2: "Norte", n3: "Área Metropolitana do Porto", am: "AMP" },
  "1305": { n1: "Continente", n2: "Norte", n3: "Tâmega e Sousa", am: null },
  "1306": { n1: "Continente", n2: "Norte", n3: "Área Metropolitana do Porto", am: "AMP" },
  "1307": { n1: "Continente", n2: "Norte", n3: "Tâmega e Sousa", am: null },
  "1308": { n1: "Continente", n2: "Norte", n3: "Área Metropolitana do Porto", am: "AMP" },
  "1309": { n1: "Continente", n2: "Norte", n3: "Tâmega e Sousa", am: null },
  "1310": { n1: "Continente", n2: "Norte", n3: "Área Metropolitana do Porto", am: "AMP" },
  "1311": { n1: "Continente", n2: "Norte", n3: "Tâmega e Sousa", am: null },
  "1312": { n1: "Continente", n2: "Norte", n3: "Área Metropolitana do Porto", am: "AMP" },
  "1313": { n1: "Continente", n2: "Norte", n3: "Área Metropolitana do Porto", am: "AMP" },
  "1314": { n1: "Continente", n2: "Norte", n3: "Área Metropolitana do Porto", am: "AMP" },
  "1315": { n1: "Continente", n2: "Norte", n3: "Área Metropolitana do Porto", am: "AMP" },
  "1316": { n1: "Continente", n2: "Norte", n3: "Área Metropolitana do Porto", am: "AMP" },
  "1317": { n1: "Continente", n2: "Norte", n3: "Área Metropolitana do Porto", am: "AMP" },
  "1318": { n1: "Continente", n2: "Norte", n3: "Área Metropolitana do Porto", am: "AMP" },
  "1401": { n1: "Continente", n2: "Oeste e Vale do Tejo", n3: "Médio Tejo", am: null },
  "1402": { n1: "Continente", n2: "Oeste e Vale do Tejo", n3: "Médio Tejo", am: null },
  "1403": { n1: "Continente", n2: "Oeste e Vale do Tejo", n3: "Lezíria do Tejo", am: null },
  "1404": { n1: "Continente", n2: "Oeste e Vale do Tejo", n3: "Lezíria do Tejo", am: null },
  "1405": { n1: "Continente", n2: "Oeste e Vale do Tejo", n3: "Lezíria do Tejo", am: null },
  "1406": { n1: "Continente", n2: "Oeste e Vale do Tejo", n3: "Lezíria do Tejo", am: null },
  "1407": { n1: "Continente", n2: "Oeste e Vale do Tejo", n3: "Lezíria do Tejo", am: null },
  "1408": { n1: "Continente", n2: "Oeste e Vale do Tejo", n3: "Médio Tejo", am: null },
  "1409": { n1: "Continente", n2: "Oeste e Vale do Tejo", n3: "Lezíria do Tejo", am: null },
  "1410": { n1: "Continente", n2: "Oeste e Vale do Tejo", n3: "Médio Tejo", am: null },
  "1411": { n1: "Continente", n2: "Oeste e Vale do Tejo", n3: "Médio Tejo", am: null },
  "1412": { n1: "Continente", n2: "Oeste e Vale do Tejo", n3: "Lezíria do Tejo", am: null },
  "1413": { n1: "Continente", n2: "Oeste e Vale do Tejo", n3: "Médio Tejo", am: null },
  "1414": { n1: "Continente", n2: "Oeste e Vale do Tejo", n3: "Lezíria do Tejo", am: null },
  "1415": { n1: "Continente", n2: "Oeste e Vale do Tejo", n3: "Lezíria do Tejo", am: null },
  "1416": { n1: "Continente", n2: "Oeste e Vale do Tejo", n3: "Lezíria do Tejo", am: null },
  "1417": { n1: "Continente", n2: "Oeste e Vale do Tejo", n3: "Médio Tejo", am: null },
  "1418": { n1: "Continente", n2: "Oeste e Vale do Tejo", n3: "Médio Tejo", am: null },
  "1419": { n1: "Continente", n2: "Oeste e Vale do Tejo", n3: "Médio Tejo", am: null },
  "1420": { n1: "Continente", n2: "Oeste e Vale do Tejo", n3: "Médio Tejo", am: null },
  "1421": { n1: "Continente", n2: "Oeste e Vale do Tejo", n3: "Médio Tejo", am: null },
  "1501": { n1: "Continente", n2: "Alentejo", n3: "Alentejo Litoral", am: null },
  "1502": { n1: "Continente", n2: "Área Metropolitana de Lisboa", n3: "Península de Setúbal", am: "AML" },
  "1503": { n1: "Continente", n2: "Área Metropolitana de Lisboa", n3: "Península de Setúbal", am: "AML" },
  "1504": { n1: "Continente", n2: "Área Metropolitana de Lisboa", n3: "Península de Setúbal", am: "AML" },
  "1505": { n1: "Continente", n2: "Alentejo", n3: "Alentejo Litoral", am: null },
  "1506": { n1: "Continente", n2: "Área Metropolitana de Lisboa", n3: "Península de Setúbal", am: "AML" },
  "1507": { n1: "Continente", n2: "Área Metropolitana de Lisboa", n3: "Península de Setúbal", am: "AML" },
  "1508": { n1: "Continente", n2: "Área Metropolitana de Lisboa", n3: "Península de Setúbal", am: "AML" },
  "1509": { n1: "Continente", n2: "Alentejo", n3: "Alentejo Litoral", am: null },
  "1510": { n1: "Continente", n2: "Área Metropolitana de Lisboa", n3: "Península de Setúbal", am: "AML" },
  "1511": { n1: "Continente", n2: "Área Metropolitana de Lisboa", n3: "Península de Setúbal", am: "AML" },
  "1512": { n1: "Continente", n2: "Área Metropolitana de Lisboa", n3: "Península de Setúbal", am: "AML" },
  "1513": { n1: "Continente", n2: "Alentejo", n3: "Alentejo Litoral", am: null },
  "1601": { n1: "Continente", n2: "Norte", n3: "Alto Minho", am: null },
  "1602": { n1: "Continente", n2: "Norte", n3: "Alto Minho", am: null },
  "1603": { n1: "Continente", n2: "Norte", n3: "Alto Minho", am: null },
  "1604": { n1: "Continente", n2: "Norte", n3: "Alto Minho", am: null },
  "1605": { n1: "Continente", n2: "Norte", n3: "Alto Minho", am: null },
  "1606": { n1: "Continente", n2: "Norte", n3: "Alto Minho", am: null },
  "1607": { n1: "Continente", n2: "Norte", n3: "Alto Minho", am: null },
  "1608": { n1: "Continente", n2: "Norte", n3: "Alto Minho", am: null },
  "1609": { n1: "Continente", n2: "Norte", n3: "Alto Minho", am: null },
  "1610": { n1: "Continente", n2: "Norte", n3: "Alto Minho", am: null },
  "1701": { n1: "Continente", n2: "Norte", n3: "Douro", am: null },
  "1702": { n1: "Continente", n2: "Norte", n3: "Alto Tâmega e Barroso", am: null },
  "1703": { n1: "Continente", n2: "Norte", n3: "Alto Tâmega e Barroso", am: null },
  "1704": { n1: "Continente", n2: "Norte", n3: "Douro", am: null },
  "1705": { n1: "Continente", n2: "Norte", n3: "Ave", am: null },
  "1706": { n1: "Continente", n2: "Norte", n3: "Alto Tâmega e Barroso", am: null },
  "1707": { n1: "Continente", n2: "Norte", n3: "Douro", am: null },
  "1708": { n1: "Continente", n2: "Norte", n3: "Douro", am: null },
  "1709": { n1: "Continente", n2: "Norte", n3: "Alto Tâmega e Barroso", am: null },
  "1710": { n1: "Continente", n2: "Norte", n3: "Douro", am: null },
  "1711": { n1: "Continente", n2: "Norte", n3: "Douro", am: null },
  "1712": { n1: "Continente", n2: "Norte", n3: "Alto Tâmega e Barroso", am: null },
  "1713": { n1: "Continente", n2: "Norte", n3: "Alto Tâmega e Barroso", am: null },
  "1714": { n1: "Continente", n2: "Norte", n3: "Douro", am: null },
  "1801": { n1: "Continente", n2: "Norte", n3: "Douro", am: null },
  "1802": { n1: "Continente", n2: "Centro", n3: "Viseu Dão Lafões", am: null },
  "1803": { n1: "Continente", n2: "Centro", n3: "Viseu Dão Lafões", am: null },
  "1804": { n1: "Continente", n2: "Norte", n3: "Tâmega e Sousa", am: null },
  "1805": { n1: "Continente", n2: "Norte", n3: "Douro", am: null },
  "1806": { n1: "Continente", n2: "Centro", n3: "Viseu Dão Lafões", am: null },
  "1807": { n1: "Continente", n2: "Norte", n3: "Douro", am: null },
  "1808": { n1: "Continente", n2: "Centro", n3: "Região de Coimbra", am: null },
  "1809": { n1: "Continente", n2: "Centro", n3: "Viseu Dão Lafões", am: null },
  "1810": { n1: "Continente", n2: "Centro", n3: "Viseu Dão Lafões", am: null },
  "1811": { n1: "Continente", n2: "Centro", n3: "Viseu Dão Lafões", am: null },
  "1812": { n1: "Continente", n2: "Norte", n3: "Douro", am: null },
  "1813": { n1: "Continente", n2: "Norte", n3: "Tâmega e Sousa", am: null },
  "1814": { n1: "Continente", n2: "Centro", n3: "Viseu Dão Lafões", am: null },
  "1815": { n1: "Continente", n2: "Norte", n3: "Douro", am: null },
  "1816": { n1: "Continente", n2: "Centro", n3: "Viseu Dão Lafões", am: null },
  "1817": { n1: "Continente", n2: "Centro", n3: "Viseu Dão Lafões", am: null },
  "1818": { n1: "Continente", n2: "Norte", n3: "Douro", am: null },
  "1819": { n1: "Continente", n2: "Norte", n3: "Douro", am: null },
  "1820": { n1: "Continente", n2: "Norte", n3: "Douro", am: null },
  "1821": { n1: "Continente", n2: "Centro", n3: "Viseu Dão Lafões", am: null },
  "1822": { n1: "Continente", n2: "Centro", n3: "Viseu Dão Lafões", am: null },
  "1823": { n1: "Continente", n2: "Centro", n3: "Viseu Dão Lafões", am: null },
  "1824": { n1: "Continente", n2: "Centro", n3: "Viseu Dão Lafões", am: null },
  "3101": { n1: "Região Autónoma da Madeira", n2: "Região Autónoma da Madeira", n3: "Região Autónoma da Madeira", am: null },
  "3102": { n1: "Região Autónoma da Madeira", n2: "Região Autónoma da Madeira", n3: "Região Autónoma da Madeira", am: null },
  "3103": { n1: "Região Autónoma da Madeira", n2: "Região Autónoma da Madeira", n3: "Região Autónoma da Madeira", am: null },
  "3104": { n1: "Região Autónoma da Madeira", n2: "Região Autónoma da Madeira", n3: "Região Autónoma da Madeira", am: null },
  "3105": { n1: "Região Autónoma da Madeira", n2: "Região Autónoma da Madeira", n3: "Região Autónoma da Madeira", am: null },
  "3106": { n1: "Região Autónoma da Madeira", n2: "Região Autónoma da Madeira", n3: "Região Autónoma da Madeira", am: null },
  "3107": { n1: "Região Autónoma da Madeira", n2: "Região Autónoma da Madeira", n3: "Região Autónoma da Madeira", am: null },
  "3108": { n1: "Região Autónoma da Madeira", n2: "Região Autónoma da Madeira", n3: "Região Autónoma da Madeira", am: null },
  "3109": { n1: "Região Autónoma da Madeira", n2: "Região Autónoma da Madeira", n3: "Região Autónoma da Madeira", am: null },
  "3110": { n1: "Região Autónoma da Madeira", n2: "Região Autónoma da Madeira", n3: "Região Autónoma da Madeira", am: null },
  "3201": { n1: "Região Autónoma da Madeira", n2: "Região Autónoma da Madeira", n3: "Região Autónoma da Madeira", am: null },
  "4101": { n1: "Região Autónoma dos Açores", n2: "Região Autónoma dos Açores", n3: "Região Autónoma dos Açores", am: null },
  "4201": { n1: "Região Autónoma dos Açores", n2: "Região Autónoma dos Açores", n3: "Região Autónoma dos Açores", am: null },
  "4202": { n1: "Região Autónoma dos Açores", n2: "Região Autónoma dos Açores", n3: "Região Autónoma dos Açores", am: null },
  "4203": { n1: "Região Autónoma dos Açores", n2: "Região Autónoma dos Açores", n3: "Região Autónoma dos Açores", am: null },
  "4204": { n1: "Região Autónoma dos Açores", n2: "Região Autónoma dos Açores", n3: "Região Autónoma dos Açores", am: null },
  "4205": { n1: "Região Autónoma dos Açores", n2: "Região Autónoma dos Açores", n3: "Região Autónoma dos Açores", am: null },
  "4206": { n1: "Região Autónoma dos Açores", n2: "Região Autónoma dos Açores", n3: "Região Autónoma dos Açores", am: null },
  "4301": { n1: "Região Autónoma dos Açores", n2: "Região Autónoma dos Açores", n3: "Região Autónoma dos Açores", am: null },
  "4302": { n1: "Região Autónoma dos Açores", n2: "Região Autónoma dos Açores", n3: "Região Autónoma dos Açores", am: null },
  "4401": { n1: "Região Autónoma dos Açores", n2: "Região Autónoma dos Açores", n3: "Região Autónoma dos Açores", am: null },
  "4501": { n1: "Região Autónoma dos Açores", n2: "Região Autónoma dos Açores", n3: "Região Autónoma dos Açores", am: null },
  "4502": { n1: "Região Autónoma dos Açores", n2: "Região Autónoma dos Açores", n3: "Região Autónoma dos Açores", am: null },
  "4601": { n1: "Região Autónoma dos Açores", n2: "Região Autónoma dos Açores", n3: "Região Autónoma dos Açores", am: null },
  "4602": { n1: "Região Autónoma dos Açores", n2: "Região Autónoma dos Açores", n3: "Região Autónoma dos Açores", am: null },
  "4603": { n1: "Região Autónoma dos Açores", n2: "Região Autónoma dos Açores", n3: "Região Autónoma dos Açores", am: null },
  "4701": { n1: "Região Autónoma dos Açores", n2: "Região Autónoma dos Açores", n3: "Região Autónoma dos Açores", am: null },
  "4801": { n1: "Região Autónoma dos Açores", n2: "Região Autónoma dos Açores", n3: "Região Autónoma dos Açores", am: null },
  "4802": { n1: "Região Autónoma dos Açores", n2: "Região Autónoma dos Açores", n3: "Região Autónoma dos Açores", am: null },
  "4901": { n1: "Região Autónoma dos Açores", n2: "Região Autónoma dos Açores", n3: "Região Autónoma dos Açores", am: null },
};
